notes/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from landing.views import PostList, PostDetail, PostCreate, PostEdit, PostDelete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^$', PostList.as_view(), name='home_page'),
    url(r'^detail/(?P<slug>[\w-]+)/$', PostDetail.as_view(), name='post_details'),
    url(r'^create/', login_required(PostCreate.as_view()), name='post_create'),
    url(r'^edit/(?P<slug>[\w-]+)/$', PostEdit.as_view(), name='post_edit'),
    url(r'^delete/(?P<slug>[\w-]+)/$', PostDelete.as_view(), name='post_delete'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/models.py
import os
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.conf import settings
from unidecode import unidecode

class Post(models.Model):
    author = models.ForeignKey(User)
    category = models.CharField(max_length=32, null=True, blank=True, verbose_name='Категория')
    title = models.CharField(max_length=128, blank=False, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Контент', null=True, blank=True)
    post_created = models.DateTimeField(auto_now_add=True, verbose_name='Пост создан')
    link = models.URLField(verbose_name='Ссылка', null=True, blank=True)
    views = models.IntegerField(default=0, verbose_name='Просмотры')
    slug = models.SlugField(null=True, db_index=True)
    relevance = models.BooleanField(default=True)
    image = models.ImageField(default='media/no_image.jpeg')
    file = models.FileField(upload_to='uploaded_files', null=True, blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.title))
        self.category = self.category.lower()
        category_image = self.category + '.jpeg'
        if os.path.exists(os.path.join(settings.MEDIA_ROOT, category_image)):
            self.image = category_image
        else:
            self.image = 'no_image.jpeg'
        super (Post, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

class Note(models.Model):
    post = models.ForeignKey(Post)
    note_comment = models.TextField(verbose_name='Заметки')
    note_url = models.URLField(verbose_name='Ссылка', null=True, blank=True)
    note_created = models.DateTimeField(auto_now=True, verbose_name='Заметка создана')

    def __str__(self):
        return self.note_comment

landing/views.py
from django.views.generic import View, CreateView, UpdateView, DeleteView, ListView
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.db.models import Q, F
from landing.models import Post, Note
from landing.form import PostForm
from .filters import CategoryFilter


class PostList(ListView):
    model = Post
    context_object_name = 'post_list'
    template_name = 'base.html'
    paginate_by = 5
    queryset = Post.objects.filter(relevance=True).order_by('-post_created')

    def get_queryset(self):
        search_param = self.request.GET.get('search', None)
        filter_param = self.request.GET.get('categories_filter', None)

        queries = Q()
        if search_param or filter_param:
            if search_param:
                splitted_search_params = search_param.split()
                for s_param in splitted_search_params:
                    queries.add(Q(title__icontains=s_param), Q.OR)
                    queries.add(Q(content__icontains=s_param), Q.OR)
            if filter_param:
                splitted_filter_param = filter_param.split()
                for f_param in splitted_filter_param:
                    queries.add(Q(category__icontains=f_param), Q.AND)
            param_query = self.queryset.filter(queries)
            if param_query.exists():
                return param_query
        return self.queryset


    def get_context_data(self, **kwargs):
        categoty_list = Post.objects.all()
        kwargs['filter'] = CategoryFilter(queryset=categoty_list)
        return super(PostList, self).get_context_data(**kwargs)

class PostDetail(View):

    def get(self, request, slug):
        context = {}
        post = Post.objects.get(slug=slug)
        post.views += 1
        post.save()
        note_list = Note.objects.filter(post=post).order_by('note_created')
        context['note_list'] = note_list
        return render(request, 'landing/post_details.html', context)

class PostCreate(CreateView):
    form_class = PostForm
    model = Post
    template_name = 'landing/create_post.html'
    success_url = reverse_lazy('home_page')

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super(PostCreate, self).form_valid(form)

class PostEdit(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'landing/post_edit.html'

    def form_valid(self, form):
        uploaded_file = self.get_form_kwargs().get('files')
        if uploaded_file:
            post_file = uploaded_file['file']
            form.file = post_file
        form.save()
        return super(PostEdit, self).form_valid(form)

    def get_success_url(self):
        if 'slug' in self.kwargs:
            slug = self.kwargs['slug']
            if self.object.category == 'url':
                return reverse_lazy('post_details', kwargs={'slug':slug})
            else:
                return reverse_lazy('home_page')
        else:
            return reverse_lazy('home_page')

class PostDelete(DeleteView):
    model = Post
    success_url = reverse_lazy('home_page')
    template_name = 'landing/delete_confirmation.html'

templates/base.html
{% load static %}
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">

<head>
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/my_styles.css' %}">
<link rel="stylesheet" href="{% static 'fonts/glyphicons-halflings-regular.woff2' %}">
<link rel="stylesheet" href="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.js" integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>
<script src={% static 'js/bootstrap.js' %}></script>

<title>
    {% block title %}
        Notes
    {% endblock %}
</title>
</head>

<body>
<!-- Start Top Bar -->
    <nav class="navbar navbar-inverse" id="topbar">
      <div class="container-fluid">
        <ul class="nav navbar-nav navbar-left">
            <li><a href={% url 'home_page' %}>Home</a></li>
            <li><a href="{% url 'post_create' %}">Add Post</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="#">{{ user.username }}</a></li>
                <li><a href="{% url 'auth_logout' %}?next={% url 'home_page' %}"> Logout</a></li>
            {% else %}
                <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
                <li><a href="{% url 'auth_login' %}">Login</a></li>
            {% endif %}
        </ul>
      </div>
    </nav>
<!-- End Top Bar -->
<div class="container">
{% block filter %}
    {% include 'landing/filters.html' %}
{% endblock %}
{% block content %}
    {% include 'landing/content.html' %}
{% endblock %}
</div>
<div id="footer">
    {% block footer %}
        <hr/>
    {% endblock %}
</div>
</body>

</html>

templates/landing/content.html
{% block content %}
    <div class="container">
        <div class="row">
            {% for post in post_list %}
                <div class="col-md-10 col-sm-9 col-xs-12">
                    <article>
                        <div class="row">
                            <div class="col-sm-6 col-md-4">
                                <figure>
                                    <img src={{ post.image.url }}>
                                </figure>
                            </div>
                            <div class="col-sm-6 col-md-8">

                                {% if post.note_set.count != 0 %}
                                    <span class="label label-default pull-right"><i class="glyphicon glyphicon-comment"></i>{{ post.note_set.count }}</span>
                                {% endif %}
                                <h5><b>{{ post.title }}</b></h5>
                                <p>{{ post.content }}</p>
                                <section>
                                    <i class="glyphicon glyphicon-folder-open"></i> {{ post.category }}
                                    <i class="glyphicon glyphicon-user"></i>{{ post.author }}
                                    <i class="glyphicon glyphicon-calendar"></i>{{ post.post_created|date }}
                                    <i class="glyphicon glyphicon-eye-open"></i>{{ post.views }}
                                </section>
                                <div class="btn-group pull-right">
                                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">More
                                        <span class="caret"></span>
                                    </button>

                                    <ul class="dropdown-menu" role="menu">
                                    {% if post.author_id == user.id %}
                                        <li><a class="dropdown-item" href="{% url 'post_edit' post.slug %}">Edit</a></li>
                                        <li><a class="dropdown-item" href="{% url 'post_delete' post.slug %}">Delete</a></li>
                                    {% endif %}

                                    {% if post.note_set.count != 0 %}
                                        <li><a class="dropdown-item" href="{% url 'post_details' post.slug %}">View all</a></li>
                                    {% endif %}

                                    {% if post.category == 'url' %}
                                        <li><a class="dropdown-item" href="{{ post.link }}">Link</a></li>
                                    {% endif %}

                                    {% if post.file %}
                                        {% if user.is_authenticated %}
                                            <li><a class="dropdown-item" href="{{ post.file.url }}">Download</a></li>
                                        {% else %}
                                            <li><a class="dropdown-item" href="{% url 'auth_login' %}">Login for download</a></li>
                                        {% endif %}
                                    {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </article>
                </div>
            {% endfor %}
        </div>
        <!-- Pagination -->
        <div class="paginator">
            {% if is_paginated %}
                <ul class="pagination">
                    {% for i in paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/landing/create_post.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
    </form>
{% endblock %}

templates/landing/delete_confirmation.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">{% csrf_token %}
<div class="container">
    <div class="row">
        <h2>
            Подтвердите удаление объекта</h2>
        <div class="col-md-12">
            <input class="btn btn-primary" type="submit" value="Подтвердить"/>
            <button onclick="window.history.back();" class="btn btn-danger" type="button">Отмена</button>
        </div>
    </div>
</div>
</form>
{% endblock %}

templates/landing/filters.html
{% block filter %}
{#    <div class="container">#}
        <div class="col-lg-offset-10">
            <form id="search" method="get" action="{% url 'home_page' %}">
                <div class="input-group">
                <input class="form-control" placeholder="Search this site" type="text" name="search">
                        <span class="input-group-btn">
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
                {{ filter.form.as_p }}
                <button class="btn btn-primary" type="submit">Filter</button>
            </form>
        </div>
{#    </div>#}
{% endblock %}

templates/landing/post_details.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        {% for note in note_list %}
            <div class="col-lg-10 col-md-8 col-sm-9 col-xs-12">
                <article>
                    <div class="row">
                        <div class="col-sm-6 col-md-4">
                            <figure>
                            <img src={{ note.post.image.url }}>
                        </figure>
                        </div>
                        <div class="col-sm-6 col-md-8">
                            <div>
                                {% if note.post.category == "video" %}
                                    <a href={{ note.note_url }}>{{ note.note_comment }}</a>
                                {% else %}
                                    <a class="button" href={{ note.note_url }}>Source Link</a><br>
                                    {% autoescape off %}
                                    {{ note.note_comment }}
                                    {% endautoescape %}
                                {% endif %}
                                <div class="mic-info">
                                    Author: {{ note.post.author }}<br> Date: {{ note.note_created }}
                                </div>
                            </div>
                        </div>
                    </div>
                </article>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/landing/post_edit.html
{% extends 'base.html' %}
{% block content %}
<form action="" enctype="multipart/form-data" method="post" >{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Edit">
</form>
{% endblock %}